### ISSUE TITLE
creation mode never end

### ISSUE THREAD

**Issue by fernandomema** [relampagorojo93/SignSelector#1]
Cuando me pide seleccionar el cartel de categoria abre un cartel y me pide que introduzca el texto de la categorai en el cartel. cuando le doy a listo no hace nada mas, si intento crear una categoria o cualquier otra cosa dice que estoy en modo creacion

When plugin ask me to select the category sign opens a poster and asks me to enter the text of the category in the sign. When I press ready does not do anything else, if I try to create a category or anything else says that I am in creation mode

**Comment by relampagorojo93** [comment]
Deberia salirte un error en ese caso. Dime la version de spigot que usas, y pasame si hay errores.

**Comment by fernandomema** [comment]
version 1.8.3 ro1
en la consola aparece este error:
ver en pastebin:
https://pastebin.com/raw/4HseReS3
ver en el comentario:

[14:09:59] [Netty Server IO #1/ERROR]: [SignSelector] Unhandled exception occured in onPacketReceiving(PacketEvent) for SignSelector
java.lang.NoClassDefFoundError: [Lnet/minecraft/server/v1_8_R3/IChatBaseComponent;
	at me.relampagorojo93.SignSelector.Main$2.onPacketReceiving(Main.java:293) ~[signselector.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib.jar:4.3.0]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [spigot.jar:git-Spigot-870264a-0a645a2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.IChatBaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_141]
	... 32 more

**Comment by relampagorojo93** [comment]
mmm tienes skype y vamos controlando? Se el porque aunque me parece algo raro.

**Comment by fernandomema** [comment]
mi skype es: fernandomema@hotmail.com

**Comment by relampagorojo93** [comment]
ERROR: Plugin incompatible with versions lower than 1.8.8. Asking on forum to get solution about the needed component compatible with lower versions. Next version (1.9 beta) will be compatible with this versions.

**Comment by relampagorojo93** [comment]
NEW ERROR: This error doesn't provide on 1.8 and 1.8.8, at least, it was noticed only on 1.8.3. Doing tests to get the error.

**Comment by relampagorojo93** [comment]
CLOSED: Personal configuration blocks the detection of protocollib
